use bytes::Bytes;

use super::super::*;

#[test]
fn test_decode_manypointers() {
    let bytes = std::fs::read("tests/test-manypointers.bin").unwrap();
    let mut data = BytesBuf::from_bytes(Bytes::copy_from_slice(&bytes));
    let message = Message::parse(&mut data).unwrap();
    let expected = Message {
        header: Header {
            id: 0,
            is_response: false,
            opcode: OpCode::Reserved(4),
            is_authoritative: false,
            is_truncated: false,
            should_recurse: false,
            recursion_available: false,
            _z: 0,
            rescode: ResCode::NoError,
            questions: 1,
            answer_records: 35,
            authority_records: 0,
            additional_records: 0,
        },
        questions: vec![Question {
            name: Domain(vec!["se".to_string()]),
            qtype: RecordType::SOA,
            qclass: RecordClass::IN,
        }],
        answers: vec![
            ResourceRecord {
                name: Domain(vec!["a".to_string(), "a".to_string(), "se".to_string()]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
            ResourceRecord {
                name: Domain(vec![
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "a".to_string(),
                    "se".to_string(),
                ]),
                rtype: RecordType::ALL,
                rclass: RecordClass::Unknown(254),
                ttl: 0,
                data: Bytes::new(),
            },
        ],
        authorities: vec![],
        additional: vec![],
    };

    assert_eq!(message, expected)
}
